### ISSUE TITLE
关于已被弃用的属性

### ISSUE THREAD

**Issue by SuibianP** [cyent/markdown-with-mkdocs-material#5]
在[yml范例](https://cyent.github.io/markdown-with-mkdocs-material/appendix/yml/)中，`extra.social.type`[已经被弃用](https://squidfunk.github.io/mkdocs-material/upgrading/#extrasocial)。
```yaml
  social:
    - type: github
      link: https://github.com/cyent
```
